!!brut.androlib.meta.MetaInfo
apkFileName: framework-res.apk
compressionType: false
doNotCompress:
- resources.arsc
- png
- jpg
- ogg
isFrameworkApk: true
packageInfo:
  forcedPackageId: '1'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '23'
  targetSdkVersion: '23'
sharedLibrary: false
sparseResources: false
unknownFiles: {}
usesFramework: null
version: 2.6.0
versionInfo:
  versionCode: '23'
  versionName: 6.0.1
